pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "maxcel_tracker_playwright:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Sachinku94/Maxcel_Trackerplaywright.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image(DOCKER_IMAGE).inside {
                        sh 'python -m pytest --alluredir=allure-results -v'
                    }
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                script {
                    sh 'allure serve allure-results'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'allure-results/**', allowEmptyArchive: true
        }
    }
}