[pytest]
addopts = --alluredir=allure-results -v
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = True
asyncio_mode = auto
markers =
    Smoke_tests: Smoke testing
    Regression_tests: Regression testing
    oauth: OAuth tests
    users: User management tests
    dashboard: Dashboard tests